<script lang="ts">
import type { ValidationError } from "../../types";
import { cardManager } from "../cardManager.svelte";

interface Props {
	onImport: (jsonData: string) => Promise<void>;
	onCancel: () => void;
}

const { onImport, onCancel }: Props = $props();

let jsonInput = $state("");
let errors = $state<ValidationError[]>([]);
let isImporting = $state(false);
let successMessage = $state("");


let parsedBundle = $state<any>(null);
let previewJson = $state("");
let isValidated = $state(false);

function _resetValidation() {
	parsedBundle = null;
	previewJson = "";
	isValidated = false;
	errors = [];
}

function handleFileUpload(event: Event) {
	const target = event.target as HTMLInputElement;
	const file = target.files?.[0];
	
	if (file) {
		const reader = new FileReader();
		reader.onload = (e) => {
			jsonInput = e.target?.result as string;
			_resetValidation();
		};
		reader.readAsText(file);
	}
}

function handleValidate() {
	errors = [];
	try {
		const parsed = JSON.parse(jsonInput);
		const validationErrors = cardManager.validateImportBundle(parsed);
		if (validationErrors && validationErrors.length > 0) {
			errors = validationErrors as ValidationError[];
			isValidated = false;
			parsedBundle = null;
			previewJson = "";
			return;
		}
		// Valid
		parsedBundle = parsed;
		previewJson = JSON.stringify(parsed, null, 2);
		isValidated = true;
	} catch (err) {
		errors = [{ field: "json", message: "Invalid JSON format" }];
		isValidated = false;
		parsedBundle = null;
		previewJson = "";
	}
}

async function handleImportFile() {
	// Attempt to validate and import the current jsonInput (for uploaded files)
	errors = [];
	if (!jsonInput || !jsonInput.trim()) {
		errors = [{ field: "input", message: "No file selected or file is empty" }];
		return;
	}

	// Validate first
	handleValidate();
	if (!isValidated) {
		// validation errors will be set by handleValidate
		return;
	}

	// Import (reuse existing import flow)
	await handleImport();
}

async function handleImport() {
	if (!isValidated || !parsedBundle) {
		errors = [{ field: "validation", message: "Please validate JSON before importing" }];
		return;
	}

	successMessage = "";
	isImporting = true;

	try {
		await onImport(previewJson);
		successMessage = "Cards imported successfully!";
		// Close modal after short delay
		setTimeout(() => {
			onCancel();
		}, 1000);
	} catch (err) {
		if (Array.isArray(err)) {
			errors = err as ValidationError[];
		} else if (err instanceof Error) {
			errors = [{ field: "general", message: err.message }];
		} else {
			errors = [{ field: "general", message: "Failed to import cards" }];
		}
	} finally {
		isImporting = false;
	}
}

function handleKeydown(e: KeyboardEvent) {
	if (e.key === "Escape") {
		onCancel();
	}
}
</script>

<div 
	class="modal-overlay" 
	onclick={(e) => e.target === e.currentTarget && onCancel()}
	onkeydown={handleKeydown}
	role="dialog"
	aria-modal="true"
	aria-labelledby="import-heading"
	tabindex="0"
>
	<div class="modal-content">
		<header>
			<h2 id="import-heading">Import Learning Cards</h2>
		</header>

		<div class="instructions">
			<p>Import cards from JSON generated by AI or exported from another project.</p>
			<p>You can either paste JSON directly or upload a .json file.</p>
		</div>

		<div class="input-methods">
			<div class="file-upload">
				<label for="file-input">
					<span class="button secondary">Choose File</span>
				</label>
				<input
					id="file-input"
					type="file"
					accept=".json,application/json"
					onchange={handleFileUpload}
				/>
				<button class="secondary import-file-btn" type="button" onclick={handleImportFile} disabled={isImporting || !jsonInput.trim()} title="Validate and import the selected file">Import File</button>
			</div>

			<div class="divider">or</div>

			<textarea
				bind:value={jsonInput}
				placeholder="Paste JSON here..."
				rows="12"
				aria-label="JSON input"
			></textarea>

			<div class="validate-actions">
				<button class="secondary" type="button" onclick={handleValidate}>Validate & Preview</button>
				{#if isValidated}
					<span class="valid-ok">✅ Valid</span>
				{/if}
			</div>
		</div>

		{#if errors.length > 0}
			<div class="errors" role="alert">
				<strong>Validation Errors:</strong>
				<ul>
					{#each errors as error}
						<li>
							{#if error.cardIndex !== undefined}
								<strong>Card {error.cardIndex + 1}:</strong>
							{/if}
							{error.message}
						</li>
					{/each}
				</ul>
			</div>
		{/if}

		{#if isValidated}
			<div class="preview-block">
				<h3>Preview</h3>
				<textarea rows="10" readonly bind:value={previewJson}></textarea>
				<p><strong>Cards:</strong> {parsedBundle?.cards?.length ?? 0}</p>
			</div>
		{/if}

		{#if successMessage}
			<div class="success" role="status">
				{successMessage}
			</div>
		{/if}

		<footer>
			<button
				class="secondary"
				onclick={onCancel}
				type="button"
				disabled={isImporting}
			>
				Cancel
			</button>
			<button
				class="primary"
				onclick={handleImport}
				type="button"
				disabled={isImporting || !isValidated}
			>
				{isImporting ? "Importing..." : "Import"}
			</button>
		</footer>
	</div>
</div>

<style>
	.modal-overlay {
		position: fixed;
		top: 0;
		left: 0;
		right: 0;
		bottom: 0;
		background: rgba(0, 0, 0, 0.5);
		display: flex;
		align-items: center;
		justify-content: center;
		z-index: 1000;
	}

	.modal-content {
		background: white;
		padding: 2rem;
		border-radius: 8px;
		max-width: 600px;
		width: 90%;
		max-height: 90vh;
		overflow-y: auto;
		box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
	}

	header h2 {
		margin: 0 0 1rem 0;
		font-size: 1.5rem;
	}

	.instructions {
		margin-bottom: 1.5rem;
		color: #666;
	}

	.instructions p {
		margin: 0.5rem 0;
	}

	.input-methods {
		margin-bottom: 1.5rem;
	}

	.file-upload {
		margin-bottom: 1rem;
		display:flex;
		gap:8px;
		align-items:center;
	}

	.file-upload .import-file-btn { padding: 0.5rem 0.75rem; }

	.file-upload input[type="file"] {
		display: none;
	}

	.file-upload label {
		cursor: pointer;
	}

	.button {
		display: inline-block;
		padding: 0.5rem 1rem;
		border-radius: 4px;
		font-weight: 500;
		cursor: pointer;
	}

	.button.secondary {
		background: #f0f0f0;
		color: #333;
	}

	.button.secondary:hover {
		background: #e0e0e0;
	}

	.divider {
		text-align: center;
		margin: 1rem 0;
		color: #999;
		font-style: italic;
	}

	textarea {
		width: 100%;
		padding: 0.75rem;
		border: 1px solid #ddd;
		border-radius: 4px;
		font-family: monospace;
		font-size: 0.875rem;
		resize: vertical;
	}

	textarea:focus {
		outline: none;
		border-color: #007bff;
	}

	.errors {
		background: #fee;
		border: 1px solid #fcc;
		border-radius: 4px;
		padding: 1rem;
		margin-bottom: 1rem;
	}

	.errors strong {
		color: #c00;
	}

	.errors ul {
		margin: 0.5rem 0 0 0;
		padding-left: 1.5rem;
	}

	.errors li {
		margin: 0.25rem 0;
		color: #600;
	}

	.success {
		background: #efe;
		border: 1px solid #cfc;
		border-radius: 4px;
		padding: 1rem;
		margin-bottom: 1rem;
		color: #060;
	}

	.preview-block {
		margin-top: 1rem;
	}

	.preview-block textarea { width: 100%; font-family: monospace; padding: 0.75rem; border-radius:4px; border: 1px solid #ddd; }

	.validate-actions { margin-top:0.5rem; display:flex; gap:8px; align-items:center; }
	.validate-actions .valid-ok { color: green; }

	button.primary {
		background: #007bff;
		color: white;
	}

	button.primary:hover:not(:disabled) {
		background: #0056b3;
	}

	button.secondary {
		background: #f0f0f0;
		color: #333;
	}

	button.secondary:hover:not(:disabled) {
		background: #e0e0e0;
	}

	button:disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}
</style>
